# Generated by Django 3.2.3 on 2021-06-11 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strikePrice', models.IntegerField()),
                ('expiryDate', models.TextField(max_length=10)),
                ('underlying', models.TextField(max_length=15)),
                ('identifier', models.TextField(max_length=50)),
                ('openInterest', models.IntegerField()),
                ('changeinOpenInterest', models.IntegerField()),
                ('pchangeinOpenInterest', models.FloatField()),
                ('totalTradedVolume', models.IntegerField()),
                ('impliedVolatility', models.FloatField()),
                ('lastPrice', models.FloatField()),
                ('change', models.FloatField()),
                ('pChange', models.FloatField()),
                ('totalBuyQuantity', models.IntegerField()),
                ('totalSellQuantity', models.IntegerField()),
                ('bidQty', models.IntegerField()),
                ('bidprice', models.FloatField()),
                ('askQty', models.IntegerField()),
                ('askPrice', models.FloatField()),
                ('underlyingValue', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NSEInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strikePrice', models.IntegerField()),
                ('expiryDate', models.TextField(max_length=10)),
                ('CE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='NSEData.maindata')),
                ('PE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='NSEData.maindata')),
            ],
        ),
    ]
