# Generated by Django 3.2.4 on 2021-06-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NSEData', '0002_alter_maindata_expirydate'),
    ]

    operations = [
        migrations.CreateModel(
            name='NSEInfoGrouped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField()),
                ('NSEInfo_start', models.IntegerField()),
                ('NSEInfo_end', models.IntegerField()),
            ],
        ),
    ]
