# Generated by Django 3.2.4 on 2021-06-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NSEData', '0003_nseinfogrouped'),
    ]

    operations = [
        migrations.CreateModel(
            name='mailList',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
